// Mock data for products () (replace with API call later)
// Remove Color section or make array

const products = [
  {
    id: 1,
    name: "Product 1",
    price: 19.99,
    image: "",
    description: "This is a description for Product 1.",
    category: ["Animals", "Anime"],
    size: 1.5,
    color: "Red",
  },
  {
    id: 2,
    name: "Product 2",
    price: 29.99,
    image: "",
    description: "This is a description for Product 2.",
    category: ["Movies & TV Shows"],
    size: 2.5,
    color: "Blue",
  },
  {
    id: 3,
    name: "Product 3",
    price: 39.99,
    image: "",
    description: "This is a description for Product 3.",
    category: ["Anime"],
    size: 3.5,
    color: "Green",
  },
  {
    id: 4,
    name: "Product 4",
    price: 49.99,
    image: "",
    description: "This is a description for Product 4.",
    category: ["Animals"],
    size: 4.5,
    color: "Blue",
  },
  {
    id: 5,
    name: "Product 5",
    price: 59.99,
    image: "",
    description: "This is a description for Product 5.",
    category: ["Anime"],
    size: 5.5,
    color: "Red",
  },
  {
    id: 6,
    name: "Product 6",
    price: 69.99,
    image: "",
    description: "This is a description for Product 6.",
    category: ["Anime"],
    size: 6.5,
    color: "Green",
  },
  {
    id: 7,
    name: "Product 7",
    price: 79.99,
    image: "",
    description: "This is a description for Product 7.",
    category: ["Animals"],
    size: 7.5,
    color: "Red",
  },
  {
    id: 8,
    name: "Product 8",
    price: 89.99,
    image: "",
    description: "This is a description for Product 8.",
    category: ["Anime"],
    size: 8.5,
    color: "Blue",
  },
  {
    id: 9,
    name: "Product 9",
    price: 99.99,
    image: "",
    description: "This is a description for Product 9.",
    category: ["Anime"],
    size: 9.5,
    color: "Green",
  },
  {
    id: 10,
    name: "Product 10",
    price: 109.99,
    image: "",
    description: "This is a description for Product 10.",
    category: ["Animals"],
    size: 0.5,
    color: "Red",
  },
  {
    id: 11,
    name: "Product 11",
    price: 119.99,
    image: "",
    description: "This is a description for Product 11.",
    category: ["Anime"],
    size: 1.5,
    color: "Blue",
  },
  {
    id: 12,
    name: "Product 12",
    price: 129.99,
    image: "",
    description: "This is a description for Product 12.",
    category: ["Anime"],
    size: 2.5,
    color: "Green",
  },
  {
    id: 13,
    name: "Product 13",
    price: 29.99,
    image: "",
    description: "This is a description for Product 13.",
    category: ["Anime"],
    size: 3.2,
    color: "Blue",
  },
  {
    id: 14,
    name: "Product 14",
    price: 9.99,
    image: "",
    description: "This is a description for Product 14.",
    category: ["Movies & TV Shows"],
    size: 4.0,
    color: "Green",
  },
  {
    id: 15,
    name: "Product 15",
    price: 49.99,
    image: "",
    description: "This is a description for Product 15.",
    category: ["Animals"],
    size: 2.5,
    color: "Black",
  },
  {
    id: 16,
    name: "Product 16",
    price: 15.99,
    image: "",
    description: "This is a description for Product 16.",
    category: ["Anime"],
    size: 1.0,
    color: "Yellow",
  },
  {
    id: 17,
    name: "Product 17",
    price: 39.99,
    image: "",
    description: "This is a description for Product 17.",
    category: ["Movies & TV Shows"],
    size: 5.0,
    color: "Orange",
  },
];

export default products;
